### ISSUE TITLE
"TypeError: too many positional arguments" when running the example in readthedocs

### ISSUE THREAD

**Issue by gilhornung** [ncbi/JUDI#3]
When running the example in https://pyjudi.readthedocs.io/en/latest/judi-tasks.html
I get the following error:

```
$ doit -f j.py
/home/ubuntu/miniconda3/envs/genomics.py3/lib/python3.7/site-packages/tqdm/std.py:699: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import Panel
global pdb :
   W  X
0  1  a
1  1  b
2  2  a
3  2  b
.  Test:X~a
>> foo files: ./judi_files/a1.txt ./judi_files/a2.txt
>> foo param db:
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/genomics.py3/lib/python3.7/site-packages/doit/doit_cmd.py", line 299, in run
    return command.parse_execute(args)
  File "/home/ubuntu/miniconda3/envs/genomics.py3/lib/python3.7/site-packages/doit/cmd_base.py", line 151, in parse_execute
    return self.execute(params, args)
  File "/home/ubuntu/miniconda3/envs/genomics.py3/lib/python3.7/site-packages/doit/cmd_base.py", line 605, in execute
    return self._execute(**exec_params)
  File "/home/ubuntu/miniconda3/envs/genomics.py3/lib/python3.7/site-packages/doit/cmd_run.py", line 265, in _execute
    return runner.run_all(self.control.task_dispatcher())
  File "/home/ubuntu/miniconda3/envs/genomics.py3/lib/python3.7/site-packages/doit/runner.py", line 255, in run_all
    self.run_tasks(task_dispatcher)
  File "/home/ubuntu/miniconda3/envs/genomics.py3/lib/python3.7/site-packages/doit/runner.py", line 221, in run_tasks
    catched_excp = self.execute_task(node.task)
  File "/home/ubuntu/miniconda3/envs/genomics.py3/lib/python3.7/site-packages/doit/runner.py", line 176, in execute_task
    return task.execute(self.stream)
  File "/home/ubuntu/miniconda3/envs/genomics.py3/lib/python3.7/site-packages/doit/task.py", line 466, in execute
    action_return = action.execute(task_stdout, task_stderr)
  File "/home/ubuntu/miniconda3/envs/genomics.py3/lib/python3.7/site-packages/doit/action.py", line 433, in execute
    kwargs = self._prepare_kwargs()
  File "/home/ubuntu/miniconda3/envs/genomics.py3/lib/python3.7/site-packages/doit/action.py", line 402, in _prepare_kwargs
    self.args, self.kwargs)
  File "/home/ubuntu/miniconda3/envs/genomics.py3/lib/python3.7/site-packages/doit/action.py", line 59, in _prepare_kwargs
    bound_args = func_sig.bind_partial(*args)
  File "/home/ubuntu/miniconda3/envs/genomics.py3/lib/python3.7/inspect.py", line 3022, in bind_partial
    return args[0]._bind(args[1:], kwargs, partial=True)
  File "/home/ubuntu/miniconda3/envs/genomics.py3/lib/python3.7/inspect.py", line 2936, in _bind
    raise TypeError('too many positional arguments') from None
TypeError: too many positional arguments
```

**Comment by soumitrakp** [comment]
Hi @gilhornung,
Thank you for bringing this to our notice. The bug is now fixed. Could you please reinstall judi (0.0.0.5) using pip and let me know how it goes?
Regards,
Soumitra
